Chapter 18/pizzeria_project/pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all pizza's.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single pizza
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

Chapter 18/pizzeria_project/pp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

Chapter 18/pizzeria_project/pizzas/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'
    
    def __str__(self):
        return self.name

Chapter 18/pizzeria_project/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for pizzas"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizzas"""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

Chapter 18/pizzeria_project/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> - 
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

Chapter 18/pizzeria_project/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
<p>Pizza's shows what toppings go with what pizza's,
    a rich selection!</p>
{% endblock content %}

Chapter 18/pizzeria_project/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

    <p>Pizza: {{ pizza.name }}</p>
    <p>Toppings:</p>
    <ul>
        {% for topping in toppings %}
        <li>{{ topping.name }}</li>
        {% empty %}
            <li>There are no toppings for this pizza yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

Chapter 18/pizzeria_project/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
        <li>
            <a href="{% url 'pizzas:pizza' pizza.id %}">
                {{ pizza.name }}</a> 
        </li>
    {% empty %}
        <li>No pizza's have been added yeat.</li>
    {% endfor %}
</ul>

{% endblock content %}